# Generated by Django 5.2.7 on 2025-11-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistsection',
            name='order',
        ),
    ]
