# Generated by Django 5.2.7 on 2025-11-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_remove_checklistsection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsection',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
