# Generated by Django 5.2.7 on 2025-11-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_checklistsection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='MVP', max_length=20),
        ),
    ]
