# Generated by Django 5.2.7 on 2025-11-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
