# Generated by Django 5.2.7 on 2025-11-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_remove_task_updated_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='defaults/Favicon.png', null=True, upload_to='projects/'),
        ),
    ]
