# Generated by Django 5.2.7 on 2025-11-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='defaults/copyLogo.png', null=True, upload_to='projects/'),
        ),
    ]
