# Generated by Django 5.2.7 on 2025-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_alter_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
