# Generated by Django 5.2.7 on 2026-01-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
